Feat/ouath
DevKor-Team/connecthon-back pull request #3
Opened 2022-07-10 08:03 UTC by overthestream

passport / route 관련 기능만 만들었구요 
user 머지 되면 보고 코드 더 작성하겠습니다 

passport 모듈에서 좀 헤매서 많이 오래걸렸네요 ,, 그래도 이게 가장 큰 기능 같으니 다음주는 더 열심히 달려보도록 하겠습니다~~!

2022-07-15 17:05 UTC, froggagul requested changes
오 github에서 리뷰 기능 처음 써봐요 (맨날 conversation 했는데)
전체적으로 구성은 잘 되어있는듯 해서 짜잘짜잘한 피드백만 드렸습니다. eslint 설정 등만 반영해주세요(특히 `utils/passport.ts`!) 반영 후 merge하셔도 됩니다. 수고하셨어요😀

2022-07-15 17:05 UTC, froggagul commented on package.json
> +    "axios": "^0.27.2",
axios 사용 안되는거 같던데 설치하신 이유가 있을까용

2022-07-15 17:05 UTC, froggagul commented on package.json
> +}
newline..부탁해용 ㅎㅎ

2022-07-15 17:05 UTC, froggagul commented on src/controllers/auth.ts
> +  passport.authenticate('local', { failureRedirect: '/login' }),
failureRedirect 등은 따로 상수로 빼서 관리하면 후에 수정할 때 편할 것 같습니다!

2022-07-15 17:05 UTC, froggagul commented on src/index.ts
> +    secret: 'keyboard cat', // 임시 secret key
이거 environment variable로 관리해야합니다..!

2022-07-15 17:05 UTC, froggagul commented on src/routes/auth.ts
> +  successRedirect: '/', failureRedirect: '/login', scope: ['profile_nickname', 'account_email'],
상수로 관리 22

2022-07-15 17:05 UTC, froggagul commented on src/services/auth/auth.ts
> +}
newline 22

2022-07-15 17:05 UTC, froggagul commented on src/services/auth/user.ts
> +  const user = await UserModel.findOne({ email, provider: provider });
`provider: provider` -> `provider`로 변환해주세요!

2022-07-15 17:05 UTC, froggagul commented on src/utils/passport.ts
> +import * as AuthService from '@/services/auth/auth'
semicolon `;` 추가해주세요!

2022-07-15 17:05 UTC, froggagul commented on src/utils/passport.ts
> +import { Strategy as GoogleStrategy } from 'passport-google-oauth20';
이 파일에만 eslint가 적용이 안되있는 것 같습니다! (semicolon, else return, dangling `_json` 등등...)

2022-07-18 06:44 UTC, overthestream commented on package.json
> +    "axios": "^0.27.2",
passport 사용 전에 직접 oauth req 보내려고 사용했었는데 잊고 안지웠었네요!!

2022-07-18 06:56 UTC, overthestream commented on src/controllers/auth.ts
> +  passport.authenticate('local', { failureRedirect: '/login' }),
좋은 리팩토링이네요 감사합니당

2022-07-18 07:00 UTC, overthestream commented on src/utils/passport.ts
> +import { Strategy as GoogleStrategy } from 'passport-google-oauth20';
eslint에 에러가 났었네요 감사합니닷

2022-07-18 13:06 UTC, merged